const experience = {
  espanol: [
    {
      title: "CLOUD ENGINEER",
      date: "Enero 2023 - Enero 2024",
      institution: "Melonn",
      description: [],
      ended: true,
      techs: [
        "Micro-frontends",
        "React JS",
        "Playwright",
        "Jest",
        "Typescript",
        "JavaScript",
        "Node",
        "Fastify",
        "Jira",
        "Material UI",
        "Styled Components",
        "Github",
        "AWS",
        "Serverless",
      ],
    },
    {
      title: "DESARROLLADOR FULLSTACK",
      date: "Marzo 2022 - Noviembre 2022",
      institution: "Mayasoft",
      description: [],
      ended: true,
      techs: [
        "React JS",
        "React Native",
        "Jest",
        "Typescript",
        "JavaScript",
        "Node",
        "Nest JS",
        "Material UI",
        "Styled Components",
        "GitLab",
        "Github",
        "AWS",
        "Google cloud",
        "Jenkins",
        "Docker",
      ],
    },
    {
      title: "DESARROLLADOR FRONTEND",
      date: "Enero 2021 - Agosto 2022",
      institution: "Binary Groups",
      description: [],
      ended: true,
      techs: [
        "Next JS",
        "React JS",
        "React Native",
        "Typescript",
        "Node",
        "Material UI",
        "GitLab",
        "GitHub",
        "AWS",
        "Native base",
      ],
    },
    {
      title: "DESARROLLADOR FRONTEND",
      date: "Noviembre 2021 - Marzo 2022",
      institution: "Woombat",
      description: [],
      ended: true,
      techs: [
        "Angular",
        "RxJS",
        "Typescript",
        "JavaScript",
        "Node",
        "Webpack",
        "Babel",
        "Material Angular",
        "styled-components",
        "GitHub",
        "Azure DevOps",
        "Serveless",
      ],
    },
    {
      title: "DESARROLLADOR FRONTEND",
      date: "Febrero 2021 - Julio 2021",
      institution: "Bitnovo",
      description: [],
      ended: true,
      techs: [
        "Next JS",
        "React",
        "Typescript",
        "Material UI",
        "styled-component",
        "redux",
        "SWR",
        "Jira",
        "GitLab",
      ],
    },
  ],
  english: [
    {
      title: "CLOUD ENGINEER",
      date: "January 2023 - January 2024",
      institution: "Melonn",
      description: [],
      ended: true,
      techs: [
        "Micro-frontends",
        "React JS",
        "Playwright",
        "Jest",
        "Typescript",
        "JavaScript",
        "Node",
        "Fastify",
        "Jira",
        "Material UI",
        "Styled Components",
        "Github",
        "AWS",
        "Serverless",
      ],
    },
    {
      title: "FULLSTACK DEVELOPER",
      date: "March 2022 - November 2022",
      institution: "Mayasoft",
      description: [],
      ended: true,
      techs: [
        "React JS",
        "React Native",
        "Jest",
        "Typescript",
        "JavaScript",
        "Node",
        "Nest JS",
        "Material UI",
        "Styled Components",
        "GitLab",
        "Github",
        "AWS",
        "Google cloud",
        "Jenkins",
        "Docker",
      ],
    },
    {
      title: "FRONTEND DEVELOPER",
      date: "January 2021 - August 2022",
      institution: "Binary Groups",
      description: [],
      ended: true,
      techs: [
        "Next JS",
        "React JS",
        "React Native",
        "Typescript",
        "Node",
        "Material UI",
        "GitLab",
        "GitHub",
        "AWS",
        "Native base",
      ],
    },
    {
      title: "FRONTEND DEVELOPER",
      date: "November 2021 - March 2022",
      institution: "Woombat",
      description: [],
      ended: true,
      techs: [
        "Angular",
        "RxJS",
        "Typescript",
        "JavaScript",
        "Node",
        "Webpack",
        "Babel",
        "Material Angular",
        "styled-components",
        "GitHub",
        "Azure DevOps",
        "Serveless",
      ],
    },
    {
      title: "FRONTEND DEVELOPER",
      date: "February 2021 - July 2021",
      institution: "Bitnovo",
      description: [],
      ended: true,
      techs: [
        "Next JS",
        "React",
        "Typescript",
        "Material UI",
        "styled-component",
        "redux",
        "SWR",
        "Jira",
        "GitLab",
      ],
    },
  ],
};

export default experience;
