const images = [
   {
      img: "https://material-ui.com/static/images/grid-list/honey.jpg",
      title: "honey",
      author: "Author",
      featured: false,
      kind: [0, 1],
      timeout: 0,
      show: true,
   },
   {
      img: "https://material-ui.com/static/images/grid-list/breakfast.jpg",
      title: "breakfast",
      author: "Author",
      featured: false,
      kind: [0, 2],
      timeout: 0,
      show: true,
   },
   {
      img: "https://material-ui.com/static/images/grid-list/burgers.jpg",
      title: "burgers",
      author: "Author",
      featured: false,
      kind: [0, 3],
      timeout: 0,
      show: true,
   },
   {
      img: "https://material-ui.com/static/images/grid-list/camera.jpg",
      title: "camera",
      author: "Author",
      featured: false,
      kind: [0, 4],
      timeout: 0,
      show: true,
   },
   {
      img: "https://material-ui.com/static/images/grid-list/hats.jpg",
      title: "hats",
      author: "Author",
      featured: false,
      kind: [0, 1],
      timeout: 0,
      show: true,
   },
   {
      img: "https://material-ui.com/static/images/grid-list/morning.jpg",
      title: "morning",
      author: "Author",
      featured: true,
      kind: [0, 2],
      timeout: 0,
      show: true,
   },
   {
      img: "https://material-ui.com/static/images/grid-list/mushroom.jpg",
      title: "mushroom",
      author: "Author",
      featured: true,
      kind: [0, 2],
      timeout: 0,
      show: true,
   },
   {
      img: "https://material-ui.com/static/images/grid-list/olive.jpg",
      title: "olive",
      author: "Author",
      featured: false,
      kind: [0, 4],
      timeout: 0,
      show: true,
   },
   {
      img: "https://material-ui.com/static/images/grid-list/plant.jpg",
      title: "plant",
      author: "Author",
      featured: false,
      kind: [0, 1],
      timeout: 0,
      show: true,
   },
   {
      img: "https://material-ui.com/static/images/grid-list/star.jpg",
      title: "star",
      author: "Author",
      featured: false,
      kind: [0, 2],
      timeout: 0,
      show: true,
   },
   {
      img: "https://material-ui.com/static/images/grid-list/vegetables.jpg",
      title: "vegetables",
      author: "Author",
      featured: false,
      kind: [0, 3],
      timeout: 0,
      show: true,
   },
];

const kinds = {
   0: "Todas",
   1: "PHP",
   2: "Python",
   3: "React JS",
   4: "Django",
};

export { images, kinds };
