import vtasesores from "const/vt_asesores";
import colcief from "const/colcief";
import bivlab from "const/bivlab";
import crowdinvestment from "const/crowdinvestment";
import deeptools from "const/deeptools";

const images = {
   espanol: [
      {
         key: "deep_tools",
         img: deeptools[0].url,
         title: "Deep tools",
         date: "Mar 28, 2020 - Oct 10, 2020",
         location: "Bucaramanga, Santander",
         role: "FullStack",
         entity: "Bivl2ab UIS",
         description: [
            "Este proyecto va enfocado a los desarrolladores de algoritmos de IA que no tienen el conocimiento para desplegar estos algoritmos con los estándares y medidas necesarias para su ejecución.",
            "El software fue pensado para gran parte de los miembros del grupo Bivl2ab debido a que muchos de estos no cuentan con dicho conocimiento.",
         ],
         techs: [
            "Python 3.8",
            "Django 3.0",
            "Celery",
            "Channels 2",
            "RxPy",
            "gRPC",
            "Docker",
            "Javascript",
            "React JS",
            "Bootstrap utilities",
            "Material UI",
            "mySQL",
         ],
         media: deeptools,
      },
      {
         key: "crowd_investment",
         img: crowdinvestment[0].url,
         title: "CrowdInvestment",
         date: "Nov 16, 2018 - Ago 29, 2019",
         location: "Bucaramanga, Santander",
         role: "FullStack",
         entity: "Mayasoft - hackathon",
         description: [
            "Este proyecto comenzó en una Hackathon organizada por Mayasoft. Al finalizar la competencia este proyecto continuo como una propuesta de proyecto final para la material Ingeniería de Software II lo cual permitió la finalizacion y su mejoramiento.",
            "El aplicativo tiene como filosofía el CrowdFounding, se basa en donaciones económicas, para conseguir financiar un determinado proyecto a cambio de recompensas, participaciones de forma altruista.",
         ],
         techs: [
            "PHP 7.2",
            "laravel 5.6",
            "MySQL",
            "JQuery",
            "Javascript",
            "Bootstrap 4",
         ],
         media: crowdinvestment,
      },
      {
         key: "bivlab",
         img: bivlab[0].url,
         title: "Bivl2ab",
         date: "Junio 6, 2019 - Agosto 23, 2019",
         location: "Bucaramanga, Santander",
         role: "FullStack",
         entity: "Bivl2ab UIS",
         description: [
            "En este proyecto se desarrollo una plataforma para la mostrar a detalle el transcurso de los proyectos de investigación de los integrantes del grupo Bivl2ab de la UIS.",
            "Permite registrar información detallada de cada unos de los proyectos, tales como los productos de cada uno de estos, artículos, conferencias, entre otros. Ademas datos esenciales durante el desarrollo del mismo como los datasets.",
         ],
         techs: [
            "PHP 7.2",
            "laravel 5.6",
            "MySQL",
            "JQuery",
            "Javascript",
            "Bootstrap 4",
         ],
         media: bivlab,
      },
      {
         key: "colcief",
         img: colcief[0].url,
         title: "ColCIEF",
         date: "Febrero 22, 2018 - Mayo 3, 2019",
         location: "Bucaramanga, Santander",
         role: "FullStack",
         entity: "Colegio Integrado Ezequiel Florián",
         description: [
            "En este proyecto se desarrollo una plataforma web para la administración de calificaciones e información estudiantil.",
            "Permite la generación de PDF con calificaciones por estudiante y por grupo. La plataforma permite la inserción de calificaciones y realiza los cálculos necesarios para encontrar la calificación final de cada alumno.",
         ],
         techs: [
            "PHP 7.2",
            "laravel 5.6",
            "MySQL",
            "JQuery",
            "Javascript",
            "Bootstrap 4",
         ],
         media: colcief,
      },
      {
         key: "vt_asesores",
         img: vtasesores[0].url,
         title: "Vt Asesores",
         date: "Dic 10, 2017 - Feb 8, 2018",
         location: "Bucaramanga, Santander",
         role: "FullStack",
         entity: "Vt Asesores",
         description: [
            "El objetivo de este proyecto era desarrollar una plataforma web para la gestión de la información durante el transcurso de un proceso legal evolucionado por la empresa VT asesores jurídicos.",
            "El aplicativo cuenta con diferentes herramientas para la administración de la información, generación de backups, filtrado de datos, entre otros.",
         ],
         techs: [
            "PHP 5.6",
            "PostgreSQL",
            "JQuery",
            "Javascript",
            "Bootstrap 4",
         ],
         media: vtasesores,
      },
   ],
   english: [
      {
         key: "deep_tools",
         img: deeptools[0].url,
         title: "Deep tools",
         date: "Mar 28, 2020 - Oct 10, 2020",
         location: "Bucaramanga, Santander",
         role: "FullStack",
         entity: "Bivl2ab UIS",
         description: [
            "This project is focused on AI algorithm developers who do not have the knowledge to deploy these algorithms with the standards and measures necessary for their execution.",
            "The software was designed for a large part of the members of the Bivl2ab group because many of them do not have such knowledge.",
         ],
         techs: [
            "Python 3.8",
            "Django 3.0",
            "Celery",
            "Channels 2",
            "RxPy",
            "gRPC",
            "Docker",
            "Javascript",
            "React JS",
            "Bootstrap utilities",
            "Material UI",
            "mySQL",
         ],
         media: deeptools,
      },
      {
         key: "crowd_investment",
         img: crowdinvestment[0].url,
         title: "CrowdInvestment",
         date: "Nov 16, 2018 - Aug 29, 2019",
         location: "Bucaramanga, Santander",
         role: "FullStack",
         entity: "Mayasoft - hackathon",
         description: [
            "This project started at a Hackathon organized by Mayasoft. At the end of the competition, this project continued as a final project proposal for the Software Engineering II material, which allowed its completion and improvement.",
            "The application's philosophy is CrowdFunding, it is based on financial donations, in order to finance a certain project in exchange for rewards, participations altruistically.",
         ],
         techs: [
            "PHP 7.2",
            "laravel 5.6",
            "MySQL",
            "JQuery",
            "Javascript",
            "Bootstrap 4",
         ],
         media: crowdinvestment,
      },
      {
         key: "bivlab",
         img: bivlab[0].url,
         title: "Bivl2ab",
         date: "June 6, 2019 - Aug 23, 2019",
         location: "Bucaramanga, Santander",
         role: "FullStack",
         entity: "Bivl2ab UIS",
         description: [
            "In this project, a platform was developed to show in detail the course of the research projects of the members of the Bivl2ab group of the UIS.",
            "It allows you to record detailed information on each of the projects, such as the products of each of these, articles, conferences, among others. In addition, essential data during its development such as datasets.",
         ],
         techs: [
            "PHP 7.2",
            "laravel 5.6",
            "MySQL",
            "JQuery",
            "Javascript",
            "Bootstrap 4",
         ],
         media: bivlab,
      },
      {
         key: "colcief",
         img: colcief[0].url,
         title: "ColCIEF",
         date: "Feb 22, 2018 - May 3, 2019",
         location: "Bucaramanga, Santander",
         role: "FullStack",
         entity: "Colegio Integrado Ezequiel Florián",
         description: [
            "In this project, a web platform was developed for the administration of grades and student information.",
            "It allows the generation of PDF with grades per student and per group. The platform allows the insertion of grades and performs the necessary calculations to find the final grade of each student.",
         ],
         techs: [
            "PHP 7.2",
            "laravel 5.6",
            "MySQL",
            "JQuery",
            "Javascript",
            "Bootstrap 4",
         ],
         media: colcief,
      },
      {
         key: "vt_asesores",
         img: vtasesores[0].url,
         title: "Vt Asesores",
         date: "Dec 10, 2017 - Feb 8, 2018",
         location: "Bucaramanga, Santander",
         role: "FullStack",
         entity: "Vt Asesores",
         description: [
            "The objective of this project was to develop a web platform for the management of information during the course of a legal process evolved by the company VT legal advisors.",
            "The application has different tools for managing information, generating backups, filtering data, among others.",
         ],
         techs: [
            "PHP 5.6",
            "PostgreSQL",
            "JQuery",
            "Javascript",
            "Bootstrap 4",
         ],
         media: vtasesores,
      },
   ],
};

export default images;
